### ISSUE TITLE
Error on v0.1.1: 'GP' object has no attribute 'X'

### ISSUE THREAD

**Issue by micahjsmith** [HDI-Project/BTB#46]
Steps to reproduce in new environment with only baytune==0.1.1 installed.

```
import btb
import btb.tuning.gp
tuner = btb.tuning.gp.GP([('n_estimators', btb.HyperParameter(btb.ParamTypes.INT, [10, 500]))])
tuner.propose()
```

The following error is produced
```
>>> tuner.propose()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/envs/tmp/lib/python3.6/site-packages/btb/tuning/gp.py", line 60, in propose
    if self.X.shape[0] < self.r_minimum:
AttributeError: 'GP' object has no attribute 'X'
```

This was not an issue when I was installing btb from commit 48db0da94a28492220ca666de80e193c50d756f6.

**Comment by micahjsmith** [comment]
without digging too much, the source distribution uploaded to PyPI doesn't have any dependencies besides `future`, so all of the modules that use scipy, numpy, and scikit_learn break immediately (in a fresh environment)

**Comment by csala** [comment]
I think that the dependency thin is a separated issue, which also needs to be addressed.

Indeed, none of the old versions, neither 48db0da94a28492220ca666de80e193c50d756f6, work on a fresh virtualenv at all because of the missing dependencies:

```
$ pip freeze
pkg-resources==0.0.0
$ pip install -e git+git@github.com:HDI-Project/BTB.git@48db0da94a28492220ca666de80e193c50d756f6#egg=btb
...skipped content...
Successfully installed btb future-0.16.0
$ python -c "import btb"
...skipped content...
ModuleNotFoundError: No module named 'numpy'
```

I'm opening a separated issue for this.

**Comment by csala** [comment]
Commit 1002808cb8ad1c7fa43dbce7f91f96420a700618 introduced the initialization of an empty `self.X` in the `__init__` method.

Adding these lines to `btb/tuning/tuner.py` seems to fix the issue:
```
 32                                                                                                     
 33         self.X_raw = None                                                                           
 34         self.y_raw = []                                                                             
 35                                                                                                     
 36         self.X = np.array([])                                                                       
 37         self.y = np.array([]) 
```
