### ISSUE TITLE
Categorical hyperparameters do not support None as input

### ISSUE THREAD

**Issue by csala** [HDI-Project/BTB#79]
* BTB version: v0.2.1
* Python version: Any
* Operating System: Any

### Description

Current Categorical Hyperparameters implementation attempts to cast any value that is given in the input param_range.

### What I Did

```
>>> from btb import HyperParameter, ParamTypes
>>> HyperParameter(ParamTypes.STRING, [None, 'a'])
<btb.hyper_parameter.StringCatHyperParameter object at 0x7f0d910a8d68>
>>> hp = HyperParameter(ParamTypes.STRING, [None, 'a'])
>>> hp.inverse_transform(0)
'None'   # <<<< this should be None, not the string 'None'
>>> HyperParameter(ParamTypes.INT_CAT, [None, 1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xals/Projects/Pythia/MIT/BTB/btb/hyper_parameter.py", line 165, in __init__
    self.cat_transform = {self.cast(each): 0 for each in param_range}
  File "/home/xals/Projects/Pythia/MIT/BTB/btb/hyper_parameter.py", line 165, in <dictcomp>
    self.cat_transform = {self.cast(each): 0 for each in param_range}
  File "/home/xals/Projects/Pythia/MIT/BTB/btb/hyper_parameter.py", line 237, in cast
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
>>> HyperParameter(ParamTypes.FLOAT_CAT, [None, 1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xals/Projects/Pythia/MIT/BTB/btb/hyper_parameter.py", line 165, in __init__
    self.cat_transform = {self.cast(each): 0 for each in param_range}
  File "/home/xals/Projects/Pythia/MIT/BTB/btb/hyper_parameter.py", line 165, in <dictcomp>
    self.cat_transform = {self.cast(each): 0 for each in param_range}
  File "/home/xals/Projects/Pythia/MIT/BTB/btb/hyper_parameter.py", line 244, in cast
    return float(value)
TypeError: float() argument must be a string or a number, not 'NoneType'
```

**Comment by csala** [comment]
This will be solved with issue #62
